project:
  type: website
  output-dir: docs
  resources: files

website:
  title: "Sugnet Lubbe"
  favicon: Sugnet.jpg
  site-url: https://github.com/sugnet/academic
  navbar:
    background: primary
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Career
        href: career.qmd
      - text: Research
        href: research.qmd  
      - text: Teaching
        href: teaching.qmd
      - text: Recognition
        href: recognition.qmd  
    right:
      - icon: github
        href: https://github.com/      

date-format: "D MMMM YYYY"

format:
  html:
    theme: 
      - pulse
      - custom.scss
    toc: true

